### PR TITLE
Fix cors support in sandbox

### PR DESCRIPTION
**Pull request by PatrickHeneise**
- [x] Forked the repository and created your branch from master
- [x] Make sure the tests pass! `npm it` in the repository root
- [ ] If you've fixed a bug or added code **more** tests are appreciated
- [ ] If you're adding a new command, removing an old command, or changing how a command works, please update the relevant documentation for the command (under the `doc/` folder)
- [x] Summarize your changes in the [changelog](https://github.com/arc-repos/architect/blob/master/changelog.md)
- [x] If you haven't already please complete the CLA

Where can I find that?

### CODE REVIEW

**Comment by brianleroux** [comment]
quick update for posterity: the issue is architect does not current support OPTIONS requests with API Gateway so to workaround you need to *not* make preflighted requests. 

[there are a bunch of conditions documented here you have to avoid](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Preflighted_requests) … which makes me want to avoid CORS moreso lol

another tip: proxy the front end so you don't need cors! using something like netlify you can do somethingn like `/api/* https://api.example.com/:splat 200`

**Comment by PatrickHeneise** [comment]
That means I'd need to serve all lambda requests with content-type 'text/plain' because 'application/json' requires CORS?

**Comment by brianleroux** [comment]
you can serve it w anything you want and that's what the client gets / setting `type: 'application/json; charset=utf8'` should just work! (and send `Content-Type`)

**Comment by PatrickHeneise** [comment]
I'll check that. The CORS conditions specify text/plain, form-data and x-www-form-urlencoded as allowed content types, not application/json.

**Pull request closed without merging**
