### PR TITLE
♻️✅ help module refactor to aid in mocking and testing, reflecting unit test to source code structure

### PR DESCRIPTION
**Pull request by filmaj**
DO NOT MERGE!
This is a 100% demonstrative stab at testing the help module, to spur a conversation around how to structure the testing in the repo.

So a few general points about this sample of changes:

1. I added sinon.js as a dev dependency to aid in spying and stubbing, so that we can exercise the code-under-test without worrying about executing stuff on the cloud or making changes to the filesystem. While it does make the test code heavier (since we have to manage these ourselves), it should keep the tests performant and lets us tease apart the behaviour of certain commands.
2. You may think there's some weird re-ordering of some of the previously "hidden" functions within modules. E.g. exposing the `read` and `log` methods of the help module. By doing so, we can more easily spy and stub these modules. Spying `log`, for example, is needed if we want to prevent the tests from cluttering output. The `log` function also exits the process which is obviously troublesome from a test running perspective 😉. There are alternatives that we can employ instead of this expose-internal-methods-on-the-exported-object, such as simply placing the entire module into its own file, but stubbing modules-that-are-functions is troublesome without introducing another dev dependency such as [proxyquire](https://www.npmjs.com/package/proxyquire). I'm fine with whatever approach, I'm simply demonstrating one of them - either work. If you have a preference, let me know and I'll happily make the switch in this PR.
3. In general, I try to keep anything executed directly from the CLI (either via the npm binary scripts or otherwise) very slim and house the logic in other modules that the CLI entrypoints consume. This is why I slimmed down `src/help/cli.js` and moved most of the logic into `src/help/index.js`. I think [`src/create/cli.js`](https://github.com/arc-repos/architect/blob/master/src/create/cli.js) is a great template to follow for all other commands: it waterfalls the `init` method which parses arc files, then proceeds with a `flags` method that parses flags, and finally delegates to `src/create/index.js` for the majority of the logic. I like this structure as the logic can be tested isolated on its own by unit testing the `src/create/index.js` module. And while we're on this topic, one idea is also to pull the `flags` function from the `cli.js` module into its own module - then we can more easily test flag parsing by unit testing that module.

With those general points out of the way, a couple recommendations/discussion points:

- I found the directory structure of the test files confusing. What makes sense to me, and a pattern I've seen in other projects, is to have the unit test files reflect the directory structure of the source files. That is, tests for the `src/create/index.js` module exist under `test/create/index.js` or similar format.
- We should talk about how y'all would like to see unit testing vs. integration (or end-to-end) testing done. Integration or e2e tests tend to be much slower, since they don't mock or stub anything out, and integrate against actual filesystem or cloud services. I would recommend we lean much heavier on writing extensive unit tests, and save the integration tests to a small set of core tests that ensure mission-critical functionality. I think it's worth discussing if y'all are willing to have e2e tests integrate with e.g. AWS or not, and if so, what account would it integrate with / who would foot that bill? And how would someone without access to this blessed AWS account run the tests locally? Also, when would the integration tests run? On every PR build? On every commit to master? Only at release-prep time, locally, from a few core contributors' machines? Food for thought. I think with a refactor of the code to make it a bit easier to unit test, it is possible that we could get away with zero integration tests.

P.S. where do I sign the CLA?

Before submitting a pull request, please make sure the you checked the following:

- [x] Forked the repository and created your branch from master
- [x] Make sure the tests pass! `npm it && npm run lint` in the repository root
- [x] If you've fixed a bug or added code **more** tests are appreciated
- [x] If you haven't already please complete the CLA

Learn more about contributing: https://arc.codes/intro/community

### CODE REVIEW

**Comment by filmaj** [comment]
I took a few more further steps in this branch to try to start matching the unit test structure to mirror the source code structure (mostly in the create source code). I also started adding the semi-tedious tests for the create 'planner' module, renamed the old semi-integration tests so the new `npm test` task doesn't pick them up (it will now run any file that ends in `test.js` under the `test/` directory).

**Comment by filmaj** [comment]
Moar updates added! I'm having fun with this.

1. I've actively axing the old integration-ish tests. It doesn't seem like they have much value from the perspective of what they are verifying. They basically just checked if running `create` blew up or not while feeding in various different kinds of arc files. These are fine as smoke tests, but they don't tell you whether architect is doing the right thing based on different arc file contents, and they also rely on valid AWS creds and creating/nuking the generated infra. There was more code in the tests for cleaning up in AWS than there was for verifying architect's logic. We can always resurrect these tests should we find value in them, but I would encourage us first to have a conversation about _what_ should we be testing in an end-to-end fashion, and why. Like I mentioned in an earlier comment, I'd focus on having any future e2e tests exercise mission-critical functionality, keep the tests coarse-grained, and assert on stuff like what infra gets created/deployed to AWS rather than on stuff like if architect threw an error or not. The error handling and logic we can exercise at a much finer-grained level of detail via the unit tests.
2. Which leads me to the unit tests. I'm adding a bunch of "shell" unit test files in this PR now, reflecting the source code structure. Most of the value in these new files currently just exist in the test names: they describe (in an aspirational manner) the trickier logic bits inside the various source modules that would be worth exercising via tests. They are empty for now, and we could even leave them empty and fill them out slowly bit by bit as code evolves in the relevant areas of the project. I have such shell unit tests in place for the event and http lambda creation code so far, but will add more as I continue to remove the old integration tests and replace them with these shell unit tests.
3. I've added a code coverage tool, [istanbul](https://www.npmjs.com/package/istanbul) as a dev dependency, and tweaked the npm scripts. The unit test running script (`npm run test:unit`) now feeds tape into istanbul and prints out a short summary of code coverage. I also added another more detailed code coverage script, `npm run test:coverage`, to get a detailed per-file report. I find it useful to run this every now and then to get a sense of how much of the project's code is untested. Worth mentioning that since the tests currently don't pull in _all_ the various source modules, the coverage reported here (currently around 28%) is high - I expect this number to drop as I continue removing the old integration tests and adding unit test shells. A possible future enhancement could be to report the code coverage on incoming PRs (pretty easy to do with istanbul).

I hope I'm on the right track here! Looking forward to hearing feedback/suggestions/complains/comments.

**Comment by brianleroux** [comment]
Quick comment: this is aces! Long wanted to improve the test suite and story. Doing a weekend wedding thing so idk when I'll get time for more feedbacks but basically STOKED 🥰

**Comment by ryanblock** [comment]
Was *just* jumping on to say the same as Brian, @filmaj this is rad! 🌈

**Comment by filmaj** [comment]
Cool, I'll keep chipping away at this. Y'all enjoy the wedding! We can chat more next week or whenever.

**Comment by ryanblock** [comment]
@fil, I'm just pulling your changes to poke around and it looks like your PR is based on the old `@architect/workflows` `3.2.17` – we've done a ton of dev in the last month, it's now `@architect/architect` at `4.1.2`.

**Comment by ryanblock** [comment]
@filmaj I'm just pulling your changes to poke around and it looks like your PR is based on the old `@architect/workflows` `3.2.17` – we've done a ton of dev in the last month, it's now `@architect/architect` at `4.1.2`.

**Comment by ryanblock** [comment]
(User error on my side, please ignore previous (now deleted) comment!)

**Comment by filmaj** [comment]
I'm pretty happy with the direction of changes in here. There's still lots to be desired: the source of many commands still has zero test coverage. Only `create`, `deploy` and `help` have some at this moment. My goal is to at least scaffold out the tests for all commands so that moving forward anyone making changes has a template to follow for the tests no matter what part of the code they are playing in.

With the pull request as it is right now, there's enough for me to go on to tackle and write tests for e.g. #185 or #187

**Comment by ryanblock** [comment]
This is rad, super grateful for your effort on this!

Can you + @brianleroux + me (just being a fly on the wall) find some time tomorrow to chat and dig in? Would tomorrow at like 9.30a or 11a PT work?

**Comment by filmaj** [comment]
Yep, sounds good, either time works for me - let me know.

**Comment by ryanblock** [comment]
Great, will send an email / invite, should I send to your adobe address?

**Comment by filmaj** [comment]
Got it, and sure, tho my gmail would be better for future reference ;)

**Comment by filmaj** [comment]
Oh yeah one thing I didn't mention in the call that I realized when I was writing tests for the `create` command was that it seems like the planner is not wired up to actually create plans for creating `@slack` endpoints?

Another random thought/question I had when looking over this code that I forgot to ask in the call: what is the difference between create, deploy and hydrate commands? I mean, I think I understand what each of them do, but my question is more around the intention behind separating these commands. What differences do each of these abstract away? This is purely educational for myself to figure out what (future) functionality should exist in which module.

**Comment by brianleroux** [comment]
found a bug in deploy but for life of me can't figure out how to push commits to this fork! check out the branch I just pushed !

**Comment by brianleroux** [comment]
k, pretty fun answering that q fil https://github.com/arc-repos/architect/issues/191

(slack endpoints was a bug! I quickly patched on master 🤡 )

**Comment by filmaj** [comment]
Woops, added you as collaborator on my fork, hopefully you can push now

**Comment by brianleroux** [comment]
git is so awesome, I can push a new branch but not to `test-refactor` 🤷‍♂️

**Comment by ryanblock** [comment]
How about we cut a new branch on the official repo, merge Fil's branch into that one, and make Fil a contributor?

**Comment by filmaj** [comment]
I got invited to the org+repo so I believe I have push access now. 😈

**Comment by filmaj** [comment]
thx for the fixes bri!

**Comment by brianleroux** [comment]
for future reference the local branch needs to be the same as the remote branch name =P 

(still have a few more tests to run to mainline this but will get thru that today!)

**Comment by brianleroux** [comment]
(still tracking a bug introduced to the sandbox fyi but I did push some commits here that fixes cors in the vtl template)

**Comment by brianleroux** [comment]
published in `@architect/architect 4.2.0`

thx @filmaj 💯

**Comment by filmaj** [comment]
O shietttttt! 🎉 

Also ❤️ the version 🌳 😏

**Pull request merged**
