### PR TITLE
New sandbox 

### LINKED ISSUE #227: Sandbox: lambdas that don't exit timeout
When a lambda function starts an interval, timeout, or anything else that prevents a node process from exiting, sandbox requests will timeout.

### minimal reproduction

```js
export.handler = async function http() {
  setTimeout(() => {}, 5000)
  return {body: 'ok'}
}
```

Even though the above handler completes immediately, the sandbox won't see the result until the process exits after 5 seconds, at which point it's already timed out.

### real-world use case

I want to use Aurora Serverless from my lambdas with `mysql.createPool`. This is totally fine to use on AWS, and can give some performance benefit, but in the sandbox every request that uses the DB will timeout due to the pool keeping connections alive.

### how to fix (maybe)

Maybe sandbox/http/invoke-lambda could eagerly detect the `__ARC__ {...}` output line and kill the process as soon as it's parsed a result?

### PR DESCRIPTION
**Pull request by grncdr**
This PR supersedes #225 and fixes #227. It's a large-ish refactoring/rewrite of the sandbox based on my previous PR comments and experience of using the sandbox to develop a small app the last few days.

## Design

This version of the sandbox uses a single `invokeLambda` implementation for both the HTTP server and the loopback server (event/queue bus). It's a modification of the existing HTTP version, and includes the multi-runtime support/scaffolding.

### sandbox/http

Generation of HTML error responses has moved into the `sandbox/http` server itself to allow using the shared `invokeLambda

### sandbox/loopback

This replaces `sandbox/events` and calls out to the same shared `invokeLambda` implementation.

### sandbox/_invoke-lambda

The shared `invokeLambda` is a modification of the previous sandbox/http/invoke-lambda. It makes the following changes:

 * returns typed errors (enables the HTTP server generate different responses)
 * expects responses to be written to fd 3 (instead of stdout with the `__ARC__` prefix). Appropriate modifications have been made to the runtimes.
 * pipes stdout/stderr (with a prefix) to the stdout/stderr of the sandbox process.
 * kills the child process after receiving a response (fixes #227).

## Checklist

- [x] Forked the repository and created your branch from master
- [x] Make sure the tests pass! `npm it` in the repository root
- [ ] If you've fixed a bug or added code **more** tests are appreciated
- [x] If you're adding a new command, removing an old command, or changing how a command works, please update the relevant documentation for the command (under the `doc/` folder)
- [x] If you haven't already please complete the CLA

### CODE REVIEW

**Comment by grncdr** [comment]
Again, I haven't really looked at tests yet, but I wanted to get feedback on the overall design first.

**Comment by brianleroux** [comment]
loving this!!! also will facilitate new types of evented stuff like streams. thinking instead of making it a rewrite we trial it as `sandbox2` and if we like it just wholesale replace. have a bunch of legacy arc apps we can test/harden just to ensure backwards compat

**Comment by grncdr** [comment]
It looks like a lot of work is being done on the sandbox by @kristoferjoseph in the last few days, and more is coming up in #237.

My work here was instigated by trying to _use_ Architect, but I don't have the time to keep up with internal development at Begin in order to get my PRs merged. As such I'm going to abandon this (and my other) PRs and hope that you all fix the same issues (`@queues` support in sandbox, npm errors etc). I've shipped the little project I started using Architect so I'm happy with using my fork until the main releases contain equivalent changes/fixes.

Thanks for the cool tools ❤️👍🛠  and please adapt my commits if they can be useful 😄

**Comment by ryanblock** [comment]
Yeah, it's been under pretty heavy development lately – the community has been flourishing and it's clear there are still so many ways to improve the project (especially in sandbox, which has been getting a lot of love).

Very sorry to see you shut down these PRs, but I totally get it.

Gonna take a crack at integrating what we can of your stuff, and I hope you'll keep finding ways to help us make this thing suck less! 🌈

**Pull request closed without merging**
