### PR TITLE
Fix websocket support in sandbox

### LINKED ISSUE #328: WebSockets broken in sandbox for ^5.5.0
**Describe the bug**
The [HTTP fallback to get-index](https://github.com/arc-repos/architect/blob/747e8980813e54bc07e7d7db9279df22c41d7dcf/src/sandbox/http/fallback.js#L14-L53) introduced with commit https://github.com/arc-repos/architect/commit/747e8980813e54bc07e7d7db9279df22c41d7dcf in v5.5.0 breaks web socket support in the sandbox.

**To Reproduce**
1. Clone `https://github.com/arc-repos/arc-example-ws`.
2. Update `@architect/architect` in `package.json` from `^5.0.7` to `5.5.0` and install.
3. Run `npx sandbox` and visit `http://localhost:3333`.
4. Type something into the input and press enter.
5. Check the network tab in the inspector of your browser and verify that the message was sent using the web socket connection but the expected response was not received.

**Expected behavior**
To receive the expected response message via web socket.

**Additional context**
Adding another `else if (req.originalUrl === '/__arc') next()` after [line 16](https://github.com/arc-repos/architect/blob/747e8980813e54bc07e7d7db9279df22c41d7dcf/src/sandbox/http/fallback.js#L16) fixes the problem, so I assume the logic below line 16 might overwrite some sort of routing logic used for the local web socket functionality. Haven't dived any deeper into the code yet, but would this make sense?

**I'd be happy to help and contribute!**

### PR DESCRIPTION
**Pull request by rschweizer**
Websocket requests are handled by a custom route in the
sandbox implementation, which needs to be considered in addition to the
configured `http` routes.

Fixes #328

### CODE REVIEW

**Comment by mikemaccana** [comment]
Ooh this seems cool, I've been stuck on 5.0 due to this. Can it get merged?

**Comment by rschweizer** [comment]
I think @ryanblock wanted @brianleroux to have a look at this, since he wrote that code :eyes:

**Comment by ryanblock** [comment]
Thanks again for your patience, folks! Merged and released in 5.6.2, thanks for knocking this out @rschweizer!

**Comment by MasterJames** [comment]
Cool. I wondered where I could learn more about the AWS non sandbox situation as far as how long a socket can be open and what the costs are for doing so etc. 
If not already I am hopeful in will be come the norm to have one end point and do everything bi directionally over sockets in a serverless lambda environment where those advantages are not punished or limited.
It certain would be acceptable to reestablish connections more frequently etc. but I am uncertain what is optimal at this time.

**Pull request merged**
